server:
  port: 8080
  servlet:
    context-path: /hotel

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/managermentreservation
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
        ddl-auto: none
    show-sql: true
    properties:
        hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect